import { getTranslations, setRequestLocale } from "next-intl/server";
import Link from "next/link";
import { Card, CardContent } from "@/components/ui/card";
import { ArrowRight } from "lucide-react";
import type { Metadata } from "next";

type Props = { params: Promise<{ locale: string }> };

const BASE_URL = "https://time.shuttlelab.org";

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  if (locale === "zh") {
    return {
      title: "当前 Unix 时间戳（在线）– 实时显示",
      description: "实时显示当前的 Unix 时间戳（秒和毫秒），每秒自动刷新。支持一键复制。",
      alternates: { canonical: `/${locale}/tools/current-unix-timestamp`, languages: { en: "/tools/current-unix-timestamp", "x-default": "/tools/current-unix-timestamp" } },
    };
  }
  return {
    title: "Current Unix Timestamp – Live Epoch Time Display",
    description: "See the current Unix timestamp updating live every second. Displayed in both seconds and milliseconds with one-click copy.",
    alternates: { canonical: locale === "en" ? "/tools/current-unix-timestamp" : `/${locale}/tools/current-unix-timestamp`, languages: { en: "/tools/current-unix-timestamp", "x-default": "/tools/current-unix-timestamp" } },
  };
}

export default async function CurrentUnixTimestampPage({ params }: Props) {
  const { locale } = await params;
  setRequestLocale(locale);

  if (locale === "zh") {
    const t = await getTranslations("toolPages");
    return (
      <div className="max-w-3xl mx-auto px-4 py-16">
        <h1 className="text-3xl font-bold tracking-tight mb-4">{t("currentUnixTimestamp.title")}</h1>
        <p className="text-lg text-muted-foreground mb-10">{t("currentUnixTimestamp.subtitle")}</p>
        <Card className="border-primary/30 bg-primary/5">
          <CardContent className="flex flex-col items-center gap-4 py-10 text-center">
            <p className="text-base font-medium">在首页查看实时 Unix 时间戳，立即复制使用。</p>
            <Link href="/zh/#tool" className="inline-flex items-center justify-center h-10 gap-1.5 rounded-lg bg-primary text-primary-foreground px-5 text-sm font-medium hover:bg-primary/80 transition-colors">
              <ArrowRight className="size-4 mr-1.5" />{t("openTool")}
            </Link>
          </CardContent>
        </Card>
        <p className="text-center text-sm text-muted-foreground mt-10">
          <Link href="/tools/current-unix-timestamp" className="underline hover:text-foreground transition-colors">{t("fullGuide")}</Link>
        </p>
      </div>
    );
  }

  const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: BASE_URL }, { "@type": "ListItem", position: 2, name: "Tools", item: `${BASE_URL}/#tool` }, { "@type": "ListItem", position: 3, name: "Current Unix Timestamp" }] };
  const howToSchema = { "@context": "https://schema.org", "@type": "HowTo", name: "How to Get the Current Unix Timestamp", description: "View the live Unix timestamp and copy it for use in code or APIs.", step: [{ "@type": "HowToStep", name: "Open the tool", text: "Navigate to the Current Unix Timestamp page on Time Shuttle." }, { "@type": "HowToStep", name: "View the live timestamp", text: "The current Unix timestamp is displayed in both seconds and milliseconds, updating every second." }, { "@type": "HowToStep", name: "Copy the timestamp", text: "Click the Copy button next to seconds or milliseconds to save the value to your clipboard." }] };
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: [
    { "@type": "Question", name: "What is the current Unix timestamp?", acceptedAnswer: { "@type": "Answer", text: "The current Unix timestamp is the number of seconds since 1970-01-01 00:00:00 UTC. It increases by 1 every second. Time Shuttle displays it live, updating every second." } },
    { "@type": "Question", name: "What is the difference between seconds and milliseconds?", acceptedAnswer: { "@type": "Answer", text: "The seconds timestamp is 10 digits; the milliseconds timestamp is 13 digits (the seconds value multiplied by 1000). Both represent the same moment." } },
    { "@type": "Question", name: "How accurate is the displayed timestamp?", acceptedAnswer: { "@type": "Answer", text: "The timestamp is generated by your browser's Date.now() API, which uses your device's system clock. Accuracy depends on your device's clock synchronization." } },
    { "@type": "Question", name: "Can I use this timestamp in my code?", acceptedAnswer: { "@type": "Answer", text: "Yes. Click Copy to save the timestamp to your clipboard, then paste it into your code, API request, or database query." } },
    { "@type": "Question", name: "Is this tool free?", acceptedAnswer: { "@type": "Answer", text: "Yes, completely free with no limits, no signup, and no ads." } },
    { "@type": "Question", name: "Is my data private?", acceptedAnswer: { "@type": "Answer", text: "Yes. The timestamp is generated entirely in your browser. No data is sent to any server." } },
  ] };
  const techArticleSchema = { "@context": "https://schema.org", "@type": "TechArticle", headline: "Current Unix Timestamp – Live Epoch Time Display", description: "A guide to understanding and using the current Unix timestamp, including seconds vs milliseconds, accuracy, and common use cases.", author: { "@type": "Organization", name: "Time Shuttle", url: BASE_URL }, publisher: { "@type": "Organization", name: "Time Shuttle", url: BASE_URL }, datePublished: "2026-01-01", dateModified: "2026-06-09", url: `${BASE_URL}/tools/current-unix-timestamp`, about: { "@type": "Thing", name: "Unix Timestamp" } };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(techArticleSchema) }} />
      <div className="max-w-3xl mx-auto px-4 py-16">
        <h1 className="text-3xl font-bold tracking-tight mb-4">Current Unix Timestamp – Live Display</h1>
        <p className="text-lg text-muted-foreground mb-8">See the current Unix timestamp updating live every second. Displayed in both seconds and milliseconds with one-click copy. Time Shuttle runs entirely in your browser.</p>
        <section className="mb-10"><h2 className="text-2xl font-semibold mb-4">What Is the Current Unix Timestamp?</h2><p className="mb-4">The current Unix timestamp is the number of seconds that have elapsed since January 1, 1970, 00:00:00 UTC (the Unix epoch). It is an ever-increasing integer that represents the current moment in time. Every second, the timestamp increments by one.</p><p className="mb-4">For example, if the current Unix timestamp is 1700000000, that means exactly 1,700,000,000 seconds have passed since the epoch. This corresponds to November 14, 2023, at 22:13:20 UTC.</p><p>The Unix timestamp is the universal time reference used by operating systems, databases, programming languages, APIs, and network protocols worldwide.</p></section>
        <section className="mb-10"><h2 className="text-2xl font-semibold mb-4">Seconds vs. Milliseconds</h2><p className="mb-4">Unix timestamps are commonly expressed in two units:</p><ul className="list-disc pl-6 space-y-2"><li><strong>Seconds (10 digits):</strong> The traditional format. For example, 1700000000.</li><li><strong>Milliseconds (13 digits):</strong> Used by JavaScript and many modern APIs. For example, 1700000000000.</li></ul><p className="mt-4">Both represent the same moment. To convert seconds to milliseconds, multiply by 1000. To convert milliseconds to seconds, divide by 1000 (or use the Unix Timestamp Converter on Time Shuttle).</p></section>
        <section className="mb-10"><h2 className="text-2xl font-semibold mb-4">How to Use the Current Timestamp</h2><ol className="list-decimal pl-6 space-y-3"><li><strong>View the live timestamp:</strong> Open this page. The current Unix timestamp is displayed in both seconds and milliseconds, updating every second.</li><li><strong>Copy the value:</strong> Click the Copy button next to seconds or milliseconds to save the timestamp to your clipboard.</li><li><strong>Paste in your code:</strong> Use the timestamp in your application code, API requests, database queries, or test data.</li></ol></section>
        <section className="mb-10"><h2 className="text-2xl font-semibold mb-4">Common Use Cases</h2><p className="mb-4"><strong>API testing:</strong> Use the current timestamp in API requests that require a timestamp parameter.</p><p className="mb-4"><strong>Cache headers:</strong> Set HTTP cache expiration headers using a Unix timestamp.</p><p className="mb-4"><strong>Database records:</strong> Store the current time as a Unix timestamp in your database.</p><p className="mb-4"><strong>Cron jobs:</strong> Schedule tasks using Unix timestamps for precise timing.</p><p><strong>Token generation:</strong> Include the current timestamp in JWT tokens or signed URLs.</p></section>
        <section className="mb-12"><h2 className="text-2xl font-semibold mb-6">Frequently Asked Questions</h2><div className="space-y-6"><Card><CardContent className="pt-6"><h3 className="font-semibold mb-2">What is the current Unix timestamp?</h3><p className="text-muted-foreground">It is the number of seconds since 1970-01-01 00:00:00 UTC. Time Shuttle displays it live, updating every second.</p></CardContent></Card><Card><CardContent className="pt-6"><h3 className="font-semibold mb-2">What is the difference between seconds and milliseconds?</h3><p className="text-muted-foreground">Seconds = 10 digits, milliseconds = 13 digits. Multiply seconds by 1000 to get milliseconds.</p></CardContent></Card><Card><CardContent className="pt-6"><h3 className="font-semibold mb-2">How accurate is the timestamp?</h3><p className="text-muted-foreground">It uses your device&apos;s system clock via Date.now(). Accuracy depends on your device&apos;s clock synchronization (NTP).</p></CardContent></Card><Card><CardContent className="pt-6"><h3 className="font-semibold mb-2">Is this tool free and private?</h3><p className="text-muted-foreground">Yes. Completely free, no signup, no ads. The timestamp is generated in your browser — no data is sent anywhere.</p></CardContent></Card></div></section>
        <div className="text-center mt-12"><Link href="/" className="inline-flex items-center justify-center h-9 gap-1.5 rounded-lg bg-primary text-primary-foreground px-4 text-sm font-medium hover:bg-primary/80 transition-colors"><ArrowRight className="size-4 mr-2" />Try Time Shuttle Free</Link></div>
      </div>
    </>
  );
}
